apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskr-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: flask-example-app-999
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: .
    repoURL: https://github.com/takami-h/flask-example-app-config
    targetRevision: HEAD
